In [ ]:
from google.colab import files

uploaded = files.upload()

Saving test.csv to test.csv
Saving train.csv to train.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [ ]:
train_df.head()

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

In [ ]:
train_df['text'] = train_df['Title'] + " " + train_df['Description']

test_df['text'] = test_df['Title'] + " " + test_df['Description']

In [ ]:
train_df.head()

,Class Index,Title,Description,text
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli...",Wall St. Bears Claw Back Into the Black (Reute...
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...,Carlyle Looks Toward Commercial Aerospace (Reu...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...,Oil and Economy Cloud Stocks' Outlook (Reuters...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...,Iraq Halts Oil Exports from Main Southern Pipe...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco...","Oil prices soar to all-time record, posing new..."

In [ ]:
label_map = {
    1: 'World',
    2: 'Sports',
    3: 'Business',
    4: 'Sci/Tech'
}

In [ ]:
train_df['category'] = train_df['Class Index'].map(label_map)

test_df['category'] = test_df['Class Index'].map(label_map)

In [ ]:
train_df.tail(20)

,Class Index,Title,Description,text,category
119980,3,Corporate Cost-Cutters Miss Out,CHICAGO (Reuters) - One of the mantras of glo...,Corporate Cost-Cutters Miss Out CHICAGO (Reut...,Business
119981,3,Murdoch will shell out \$44 mil. for Manhattan...,"NEW YORK -- Rupert Murdoch, the billionaire CE...",Murdoch will shell out \$44 mil. for Manhattan...,Business
119982,1,AU Says Sudan Begins Troop Withdrawal from Dar...,Reuters - The African Union said on Saturday t...,AU Says Sudan Begins Troop Withdrawal from Dar...,World
119983,1,Insurgents Attack Iraq Election Offices (Reuters),Reuters - Insurgents have launched attacks\on ...,Insurgents Attack Iraq Election Offices (Reute...,World
119984,1,Syria Redeploys Some Security Forces in Lebano...,"Reuters - Syria, under intense pressure to qui...",Syria Redeploys Some Security Forces in Lebano...,World
119985,1,Security Scare Closes British Airport (AP),AP - Police arrested a Libyan man and blew up ...,Security Scare Closes British Airport (AP) AP ...,World
119986,1,Iraqi Judges Start Quizzing Saddam Aides (AP),AP - Iraqi judges on Saturday started interrog...,Iraqi Judges Start Quizzing Saddam Aides (AP) ...,World
119987,1,Musharraf says won't quit as army chief (Reuters),Reuters - Pakistani President Pervez Musharraf...,Musharraf says won't quit as army chief (Reute...,World
119988,1,Navy to go on PR 'offensive' to repair battere...,Canadian Press - HALIFAX (CP) - They have beco...,Navy to go on PR 'offensive' to repair battere...,World
119989,2,"NBA Wrap: Wade, O'Neal Carry Heat to 7th Strai...",NEW YORK (Reuters) - Dwyane Wade scored 25 po...,"NBA Wrap: Wade, O'Neal Carry Heat to 7th Strai...",Sports
119990,1,Barack Obama Gets #36;1.9 Million Book Deal (AP),"AP - U.S. Sen.-elect Barack Obama, whose 1995 ...",Barack Obama Gets #36;1.9 Million Book Deal (...,World
119991,2,Rauffer Beats Favorites to Win Downhill,"VAL GARDENA, Italy (Reuters) - Max Rauffer be...",Rauffer Beats Favorites to Win Downhill VAL G...,Sports
119992,1,Iraqis Face Winter Shivering by Candlelight,BAGHDAD (Reuters) - As if the daily struggle ...,Iraqis Face Winter Shivering by Candlelight B...,World
119993,1,AU Says Sudan Begins Troop Withdrawal from Darfur,ABUJA (Reuters) - The African Union said on S...,AU Says Sudan Begins Troop Withdrawal from Dar...,World
119994,1,Syria Redeploys Some Security Forces in Lebanon,"BEIRUT (Reuters) - Syria, under intense press...",Syria Redeploys Some Security Forces in Lebano...,World
119995,1,Pakistan's Musharraf Says Won't Quit as Army C...,KARACHI (Reuters) - Pakistani President Perve...,Pakistan's Musharraf Says Won't Quit as Army C...,World
119996,2,Renteria signing a top-shelf deal,Red Sox general manager Theo Epstein acknowled...,Renteria signing a top-shelf deal Red Sox gene...,Sports
119997,2,Saban not going to Dolphins yet,The Miami Dolphins will put their courtship of...,Saban not going to Dolphins yet The Miami Dolp...,Sports
119998,2,Today's NFL games,PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...,Today's NFL games PITTSBURGH at NY GIANTS Time...,Sports
119999,2,Nets get Carter from Raptors,INDIANAPOLIS -- All-Star Vince Carter was trad...,Nets get Carter from Raptors INDIANAPOLIS -- A...,Sports

In [ ]:
train_df[['Class Index', 'category']].head()

   Class Index  category
0            3  Business
1            3  Business
2            3  Business
3            3  Business
4            3  Business

In [ ]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stop_words = set(stopwords.words('english'))

In [ ]:
def preprocess_text(text):
  # convert text to lowercase
    text = text.lower()
     # remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
     # tokenize text
    words = word_tokenize(text)
     # remove stopwords
    words = [word for word in words if word not in stop_words]
      # join words back
    return " ".join(words)

In [ ]:


train_df['clean_text'] = train_df['text'].apply(preprocess_text)

test_df['clean_text'] = test_df['text'].apply(preprocess_text)

In [ ]:
train_df[['clean_text']].head()

                                          clean_text
0  wall st bears claw back black reuters reuters ...
1  carlyle looks toward commercial aerospace reut...
2  oil economy cloud stocks outlook reuters reute...
3  iraq halts oil exports main southern pipeline ...
4  oil prices soar alltime record posing new mena...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer(max_features=5000)

In [ ]:
X_train = vectorizer.fit_transform(train_df['clean_text'])

In [ ]:
X_test = vectorizer.transform(test_df['clean_text'])

In [ ]:
y_train = train_df['Class Index']

y_test = test_df['Class Index']

In [ ]:
X_train.shape

(120000, 5000)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9031578947368422

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.92      0.90      0.91      1900
           2       0.94      0.98      0.96      1900
           3       0.87      0.87      0.87      1900
           4       0.88      0.87      0.87      1900

    accuracy                           0.90      7600
   macro avg       0.90      0.90      0.90      7600
weighted avg       0.90      0.90      0.90      7600

In [ ]:
def predict_news_category(text):

    # preprocess text
    cleaned_text = preprocess_text(text)

    # convert to tf-idf vector
    vectorized_text = vectorizer.transform([cleaned_text])

    # predict category
    prediction = model.predict(vectorized_text)[0]

    # map label to category
    label_map = {
        1: 'World',
        2: 'Sports',
        3: 'Business',
        4: 'Sci/Tech'
    }

    return label_map[prediction]

In [ ]:
sample_news = """
Apple launches new AI-powered iPhone chip with advanced machine learning capabilities.
"""

print(predict_news_category(sample_news))

Sci/Tech

In [ ]:
sample_news = """
India defeated Australia in the cricket world cup final after a brilliant batting performance.
"""
print(predict_news_category(sample_news))

Sports

In [ ]:
sample_news = """
Global stock markets fell sharply as inflation concerns impacted investor confidence.
"""
print(predict_news_category(sample_news))

Business

In [ ]:
sample_news = """
Normally clannish and agressive Argentine ants have become so laid back since arriving in Australia decades ago that they no longer fight neighboring nests and have formed a supercolony here that spans 60 miles, scientists say."""
print(predict_news_category(sample_news))

Sci/Tech

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.4.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 122.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import spacy
from collections import Counter
from string import punctuation

In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
text = """
India defeated Australia in the cricket world cup final after a brilliant batting performance.

Virat Kohli scored a magnificent century and led the team to victory.

Fans celebrated across the country after the historic win.

Experts called it one of the greatest cricket finals ever played.
"""

In [ ]:
doc = nlp(text)

In [ ]:
for sent in doc.sents:
    print(sent)

India defeated Australia in the cricket world cup final after a brilliant batting performance.


Virat Kohli scored a magnificent century and led the team to victory.


Fans celebrated across the country after the historic win.


Experts called it one of the greatest cricket finals ever played.

In [ ]:
stop_words = list(spacy.lang.en.stop_words.STOP_WORDS)

In [ ]:
word_frequencies = {}

for word in doc:

    if (
        word.text.lower() not in stop_words
        and word.text.lower() not in punctuation
        and word.text.strip() != ""
    ):

        if word.text.lower() not in word_frequencies:
            word_frequencies[word.text.lower()] = 1

        else:
            word_frequencies[word.text.lower()] += 1

In [ ]:
print(word_frequencies)

{'india': 1, 'defeated': 1, 'australia': 1, 'cricket': 2, 'world': 1, 'cup': 1, 'final': 1, 'brilliant': 1, 'batting': 1, 'performance': 1, 'virat': 1, 'kohli': 1, 'scored': 1, 'magnificent': 1, 'century': 1, 'led': 1, 'team': 1, 'victory': 1, 'fans': 1, 'celebrated': 1, 'country': 1, 'historic': 1, 'win': 1, 'experts': 1, 'called': 1, 'greatest': 1, 'finals': 1, 'played': 1}

In [ ]:
max_frequency = max(word_frequencies.values())

In [ ]:
for word in word_frequencies.keys():
    word_frequencies[word] = (
        word_frequencies[word] / max_frequency
    )

In [ ]:
print(word_frequencies)

{'india': 0.5, 'defeated': 0.5, 'australia': 0.5, 'cricket': 1.0, 'world': 0.5, 'cup': 0.5, 'final': 0.5, 'brilliant': 0.5, 'batting': 0.5, 'performance': 0.5, 'virat': 0.5, 'kohli': 0.5, 'scored': 0.5, 'magnificent': 0.5, 'century': 0.5, 'led': 0.5, 'team': 0.5, 'victory': 0.5, 'fans': 0.5, 'celebrated': 0.5, 'country': 0.5, 'historic': 0.5, 'win': 0.5, 'experts': 0.5, 'called': 0.5, 'greatest': 0.5, 'finals': 0.5, 'played': 0.5}

In [ ]:
sentence_scores = {}

for sent in doc.sents:

    for word in sent:

        if word.text.lower() in word_frequencies:

            if sent not in sentence_scores:
                sentence_scores[sent] = word_frequencies[word.text.lower()]

            else:
                sentence_scores[sent] += word_frequencies[word.text.lower()]

In [ ]:
print(sentence_scores)

{
India defeated Australia in the cricket world cup final after a brilliant batting performance.

: 5.5, Virat Kohli scored a magnificent century and led the team to victory.

: 4.0, Fans celebrated across the country after the historic win.

: 2.5, Experts called it one of the greatest cricket finals ever played.
: 3.5}

In [ ]:
import joblib

joblib.dump(model, "news_classifier_model.pkl")

joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [ ]:
%%writefile app.py

import streamlit as st

st.title("Hello")

Writing app.py

In [ ]:
!ls

app.py			   sample_data	tfidf_vectorizer.pkl
news_classifier_model.pkl  test.csv	train.csv

In [ ]:
!pip install streamlit pyngrok

Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.1)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 66.6 MB/s eta 0:00:00
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 91.3 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.2 pyngrok-8.1.2 streamlit-1.57.0

In [ ]:
!streamlit run app.py &>/content/logs.txt &

In [ ]:
!ngrok config add-authtoken 3DfwdnbuWovah2i0IZ7DUCHOgTR_2kmtoj73MHHozo8kXLFM6

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

In [ ]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)

print(public_url)

NgrokTunnel: "https://embroider-eligible-overwrite.ngrok-free.dev" -> "http://localhost:8501"

In [ ]:
%%writefile app.py

Overwriting app.py

In [ ]:
%%writefile app.py

import streamlit as st
import joblib
import re
import spacy

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from string import punctuation
from heapq import nlargest

# load spacy model
nlp = spacy.load("en_core_web_sm")

# load trained model and vectorizer
model = joblib.load("news_classifier_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# stopwords
stop_words = set(stopwords.words('english'))

# preprocessing function
def preprocess_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = word_tokenize(text)

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

# prediction function
def predict_news_category(text):

    cleaned_text = preprocess_text(text)

    vectorized_text = vectorizer.transform([cleaned_text])

    prediction = model.predict(vectorized_text)[0]

    label_map = {
        1: 'World',
        2: 'Sports',
        3: 'Business',
        4: 'Sci/Tech'
    }

    return label_map[prediction]

# summarization function
def summarize_text(text):

    doc = nlp(text)

    word_frequencies = {}

    for word in doc:

        if (
            word.text.lower() not in stop_words
            and word.text.lower() not in punctuation
            and word.text.strip() != ""
        ):

            if word.text.lower() not in word_frequencies:
                word_frequencies[word.text.lower()] = 1

            else:
                word_frequencies[word.text.lower()] += 1

    max_frequency = max(word_frequencies.values())

    for word in word_frequencies.keys():
        word_frequencies[word] = (
            word_frequencies[word] / max_frequency
        )

    sentence_scores = {}

    for sent in doc.sents:

        for word in sent:

            if word.text.lower() in word_frequencies:

                if sent not in sentence_scores:
                    sentence_scores[sent] = word_frequencies[word.text.lower()]

                else:
                    sentence_scores[sent] += word_frequencies[word.text.lower()]

    summary_sentences = nlargest(
        2,
        sentence_scores,
        key=sentence_scores.get
    )

    final_summary = " ".join(
        [sent.text for sent in summary_sentences]
    )

    return final_summary

# streamlit UI
st.title("Smart News Classification & Summarization")

st.write("Paste a news article below to classify and summarize it.")

user_input = st.text_area("Enter News Article")

if st.button("Analyze Article"):

    if user_input.strip() != "":

        category = predict_news_category(user_input)

        summary = summarize_text(user_input)

        st.subheader("Predicted Category")
        st.success(category)

        st.subheader("Article Summary")
        st.write(summary)

    else:

        st.warning("Please enter a news article.")

Overwriting app.py

In [ ]:
!pkill streamlit

In [ ]:
!streamlit run app.py &>/content/logs.txt &